### ISSUE TITLE
All the live TV needs to be one after another... Means this needs to be row wise.

### ISSUE THREAD

**Issue by ahayder** [dream-diver/shob-khobor#48]
![image](https://user-images.githubusercontent.com/2572383/64462564-b064cc80-d122-11e9-9e84-4c72a0200ba1.png)

**Comment by ahayder** [comment]
I tried a new funky design trend. Please reconsider the issue again.

**Comment by ahayder** [comment]
@ashiq007-009 please close the issue if you think this design will work for now.

**Comment by imranulmean** [comment]
we fixed the desing ... hope it's done now

**Comment by ashiq007-009** [comment]
Could make sure all Online TV is working as some of them are not. 
also, can we make the icon a bit bigger so that at least 2 online TV channel can take place here instead of 3. (same as the newspaper you added 2 per column)

**Comment by ahayder** [comment]
@imranulmean please look into that issue.
