### ISSUE TITLE
The was a request to improve the weather icon, information, style 

### ISSUE THREAD

**Issue by ashiq007-009** [dream-diver/shob-khobor#57]
the weather doesn't look nice.
could you look into the below web pls to see the possibilities to add those in the apps?
https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.google.com%2Fsearch%3Fsafe%3Dactive%26ei%3DNVpxXbr5Cu_bz7sP8rO_iA0%26q%3Dweather%2520forecast%2520with%2520location%26oq%3Dweather%2520forecast%2520using%2520locatio%26gs_l%3Dpsy-ab.1.0.0i22i30l2j0i8i13i30.23434.29005..31637...0.2..0.184.2046.0j14......0....1..gws-wiz.......0i71j0j0i20i263j33i22i29i30.1wtG7vxpfXI%26fbclid%3DIwAR0voSRl-IBb4taLmRy5mxLpSueDlu32vYpXfxD2QVXqpbwEe3zsjHrSD-Y&h=AT0LcebskA214pkXK6Sg5DdLPRwr8BcORC57PNhS8YTUg77OTSgMQ5fqbv2nypws_go1ZTdNktFeSOL7qOzOJzsdmG50aXe6VW-w7z4iOo6uco3YIUZtzOPRgQVZvm6mTWNLnw
![69798476_2971604763064066_8215186712465244160_n](https://user-images.githubusercontent.com/55035369/64636886-764a4200-d424-11e9-827e-aff71dfd070b.jpg)

**Comment by ashiq007-009** [comment]
more links may we can use ... 
https://www.accuweather.com/en/bd/dhaka/28143/weather-forecast/28143?fbclid=IwAR3JTrwtBO09qsMHFCV4dlwsrQ_bJM-a8VLympIQk8X6DctUevMdtW5fSS4
https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.bbc.com%2Fweather%2F1185241%5C%3Ffbclid%3DIwAR0QY_QqusF3oCn1ddduHPjI5hCdHUVz6wavFSSHVuJMcC9FGRSsoKqXIz0&h=AT0LcebskA214pkXK6Sg5DdLPRwr8BcORC57PNhS8YTUg77OTSgMQ5fqbv2nypws_go1ZTdNktFeSOL7qOzOJzsdmG50aXe6VW-w7z4iOo6uco3YIUZtzOPRgQVZvm6mTWNLnw
https://l.facebook.com/l.php?u=https%3A%2F%2Fopenweathermap.org%2F%3Ffbclid%3DIwAR0DZ7ryu9adbHqzcNliLWaODaEWaY3nm9BRnDxcRM9jP1rBrG0FCRrt0ZA&h=AT0LcebskA214pkXK6Sg5DdLPRwr8BcORC57PNhS8YTUg77OTSgMQ5fqbv2nypws_go1ZTdNktFeSOL7qOzOJzsdmG50aXe6VW-w7z4iOo6uco3YIUZtzOPRgQVZvm6mTWNLnw

**Comment by ahayder** [comment]
Thanks for reall detail issue. We'll look into it asap

**Comment by ahayder** [comment]
@imranulmean

**Comment by ahayder** [comment]
we are working on it. @imranulmean please find the icon pack as an attachment.
[2044004-weather.zip](https://github.com/dream-diver/shob-khobor/files/3611948/2044004-weather.zip)

**Comment by imranulmean** [comment]
Added thermometer according to temperature .......

**Comment by ahayder** [comment]
nice work @imranulmean.
